# use a random unassigned HTTP port by scanning for free port
server:
  port: 8766
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://userB:pwdB@localhost:8761/eureka/

# For Spring Actuator /info endpoint
info:
    artifact: author
    name: author
    description: Author Service
    version: 1.0.0

#eureka.instance.initial-status=OUT_OF_SERVICE

security:
  auth:
    users:
      userA:
        password: pwdA
      userB:
        password: pwdB