server:
  port: 8761

# settings registerWithEureka and fetchRegistry are set to false
# meaning that this Server is not part of a cluster
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

info:
    artifact: ${project.artifactId}
    name: ${spring.application.name}
    description: ${project.description}
    version: ${project.version}

security:
  auth:
    users:
      userA:
        password: pwdA
      userB:
        password: pwdB
      userC:
        password: pwdC
      userD:
        password: pwdD
      userE:
        password: pwdE

#spring:
#  main:
#    banner-mode: "off"