# use a random unassigned HTTP port by scanning for free port
server:
  port: 8769
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}} 
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://userE:pwdE@localhost:8761/eureka/

# For Spring Actuator /info endpoint
info:
    artifact: bookcomposite
    name: bookcomposite
    description: 1.0.0
    version: Composite Book Service