# use a random unassigned HTTP port by scanning for free port
server:
  port: 8768
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}  
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://userD:pwdD@localhost:8761/eureka/

# For Spring Actuator /info endpoint
info:
    artifact: review
    name: review
    description: Review Service
    version: 1.0.0
